version: '3.8'

services:
  servicio_noticias:
    build: .
    ports:
      - "50052:50051" # Map to port 50052 on host to avoid conflict with find-news-by-descriptor on 50051
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - consorcio-red

networks:
  consorcio-red:
    external: true

