# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import noticias_pb2 as noticias__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in noticias_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReceptorNoticiasStub:
    """El servicio que escucha peticiones
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnviarNoticia = channel.unary_unary(
                '/noticias.ReceptorNoticias/EnviarNoticia',
                request_serializer=noticias__pb2.Noticia.SerializeToString,
                response_deserializer=noticias__pb2.Respuesta.FromString,
                _registered_method=True)


class ReceptorNoticiasServicer:
    """El servicio que escucha peticiones
    """

    def EnviarNoticia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReceptorNoticiasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnviarNoticia': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarNoticia,
                    request_deserializer=noticias__pb2.Noticia.FromString,
                    response_serializer=noticias__pb2.Respuesta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'noticias.ReceptorNoticias', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('noticias.ReceptorNoticias', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReceptorNoticias:
    """El servicio que escucha peticiones
    """

    @staticmethod
    def EnviarNoticia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noticias.ReceptorNoticias/EnviarNoticia',
            noticias__pb2.Noticia.SerializeToString,
            noticias__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
