# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: noticias.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'noticias.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enoticias.proto\x12\x08noticias\"s\n\x07Noticia\x12\x12\n\nid_noticia\x18\x01 \x01(\x05\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x10\n\x08id_autor\x18\x03 \x01(\x05\x12\x14\n\x0cid_categoria\x18\x04 \x01(\x05\x12\r\n\x05texto\x18\x05 \x01(\t\x12\r\n\x05\x66\x65\x63ha\x18\x06 \x01(\t\"+\n\tRespuesta\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t2K\n\x10ReceptorNoticias\x12\x37\n\rEnviarNoticia\x12\x11.noticias.Noticia\x1a\x13.noticias.Respuestab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'noticias_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTICIA']._serialized_start=28
  _globals['_NOTICIA']._serialized_end=143
  _globals['_RESPUESTA']._serialized_start=145
  _globals['_RESPUESTA']._serialized_end=188
  _globals['_RECEPTORNOTICIAS']._serialized_start=190
  _globals['_RECEPTORNOTICIAS']._serialized_end=265
# @@protoc_insertion_point(module_scope)
