
services:
  postgres:
    build: 
      context: ../database
      dockerfile: Dockerfile
    image: my-postgres-db:latest
    container_name: local-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  news-load-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: local-news-load-service
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
