services:
  news-load-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: local-news-load-service
    ports:
      - "8020:8000"
    networks:
      - consorcio-red
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres

networks:
  consorcio-red:
    external: true