# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/news_search.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'protos/news_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protos/news_search.proto\x12\x0bnews_search\"#\n\rSearchRequest\x12\x12\n\ndescriptor\x18\x01 \x01(\t\"u\n\x08NewsItem\x12\x0f\n\x07news_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\x12\x13\n\x0b\x63\x61tegory_id\x18\x04 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\"5\n\x0eSearchResponse\x12#\n\x04news\x18\x01 \x03(\x0b\x32\x15.news_search.NewsItem2d\n\x11NewsSearchService\x12O\n\x12SearchByDescriptor\x12\x1a.news_search.SearchRequest\x1a\x1b.news_search.SearchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.news_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=41
  _globals['_SEARCHREQUEST']._serialized_end=76
  _globals['_NEWSITEM']._serialized_start=78
  _globals['_NEWSITEM']._serialized_end=195
  _globals['_SEARCHRESPONSE']._serialized_start=197
  _globals['_SEARCHRESPONSE']._serialized_end=250
  _globals['_NEWSSEARCHSERVICE']._serialized_start=252
  _globals['_NEWSSEARCHSERVICE']._serialized_end=352
# @@protoc_insertion_point(module_scope)
