version: '3.8'

services:
  new-subscriptions:
    build: .
    ports:
      - "8030:8000"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=sistema_db
      - DB_USER=admin
      - DB_PASSWORD=secreta
    networks:
      - consorcio-red

networks:
  consorcio-red:
    external: true