version: '3.8'

services:
  new-subscriptions:
    build: .
    ports:
      - "8030:8000"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - consorcio-red

networks:
  consorcio-red:
    external: true
