version: '3.8'

services:
  send_news:
    build: .
    ports:
      - "8765:8765" # Puerto WebSocket
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_NAME=noticias_db
      - DB_USER=postgres
      - DB_PASS=admin
      - RABBITMQ_HOST=rabbitmq
    networks:
      - consorcio-red

networks:
  consorcio-red:
    external: true

